### ISSUE TITLE
Full refactoring

### ISSUE THREAD

**Issue by ghaiklor** [building5/sails-hook-bunyan#9]
My proposal is:
- Rewrite to ES6 syntax;
- Update all dependencies;
- Integrate greenkeeper.io;
- Integrate Travis CI and Coveralls;

I can do all this by myself and will be easier if you add me to Collaborators, so I can manage updates and fixes.

**Comment by leedm777** [comment]
@ghaiklor 

> - Rewrite to ES6 syntax;

Meh. It's < 200 lines of code. The benefits of ES2016 would be lost in the hassle of debugging with the transpiler in the way.

> - Update all dependencies;

Updated. It was just dev dependencies (jscs and chai), so I didn't push a new version to NPM.

> - Integrate greenkeeper.io;

I added a [David](david-dm.org) badge, because it was easy and I like the name. Greenkeeper looks interesting. I may start using that for this and my other projects.

> - Integrate Travis CI and Coveralls;

That's interesting. I'd gladly accept PRs adding configuration for them.
